app = "chaindrop-server"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "info"
  MONITOR_ENABLED = "true"

[http_service]
  internal_port = 2567
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 2567

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
